### ISSUE TITLE
Zero trial days - possible to create a subscription?

### ISSUE THREAD

**Issue by nathhenry3** [Tychobra/polishedpayments#11]
Hi guys,

I notice in app_module.R that it is not possible to create a subscription unless the number of trial days is > 0 - see code snippet below: 

```
if (getOption("pp")$trial_period_days > 0) {
          # add the subscription to polished
          stripe_subscription_id <- create_stripe_subscription(
            customer_id,
            plan_to_enable = getOption("pp")$prices[[1]],
            days_remaining = getOption("pp")$trial_period_days
          )
        } else {
          # there is no trial period, and the user has not enabled a payment method,
          # so we cannot go ahead and set up a subscription.
          stripe_subscription_id <- NA

        }
```

Is there any way to enable this, or is this a feature of Stripe that you must have a trial period?

Thanks a lot!

**Comment by merlinoa** [comment]
I'm actually working on this now.  Should be ready tomorrow.

**Comment by nathhenry3** [comment]
Thank you! You guys are legends

**Comment by merlinoa** [comment]
haha thanks! 

It should work now.  You'll need to install the latest version of polished from GitHub using `remotes::install_github("tychobra/polished")` and then restart your R session.

I went ahead and made a bunch of long overdue changes to the API to get this working, so it is likely that I introduced a couple bugs.  I'll work on cleaning up any bugs over the next few days.  Let me know if you run into any issues!

**Comment by nathhenry3** [comment]
It appears that there may still be an issue when dealing with NULL values - here's the error message I get:

```

<simpleError in if (is.na(sub_db$stripe_subscription_id)) {    shiny::updateQueryString(queryString = "?page=account", session = session,         mode = "replace")    session$reload()} else {    stripe_sub <- get_stripe_subscription(sub_db$stripe_subscription_id)    if (stripe_sub$trial_days_remaining > 0 || !is.na(stripe_sub$default_payment_method)) {        session$userData$subscription(list(free_user = FALSE,             price_id = stripe_sub$plan_id, nickname = stripe_sub$nickname,             is_billing_enabled = if (is.na(stripe_sub$default_payment_method)) FALSE else TRUE,             trial_days_remaining = stripe_sub$trial_days_remaining))        return()    }    else {        shiny::updateQueryString(queryString = "?page=account",             session = session, mode = "replace")        session$reload()    }}: argument is of length zero>

```

**Comment by merlinoa** [comment]
Whoops! I think it should work now.  Please install the latest dev versions of {polished} and {polishedpayments}.

**Comment by merlinoa** [comment]
For some reason I am not getting the same error.  When you have a minute, can you please pull the latest and give it another shot?  I improved the error message, and I'm hoping this new error message will help us resolve this most recent bug.

**Comment by nathhenry3** [comment]
Ok so the new error I'm seeing is the following, as soon as the payments screen appears (this doesn't occur for the free_user role):

```
[1] "unable to get invoices"
<simpleError: list(code = "resource_missing", doc_url = "https://stripe.com/docs/error-codes/resource-missing", message = "No such customer: 'cus_JxVeQfN74BGSmk'; a similar object exists in test mode, but a live mode key was used to make this request.", param = "customer", type = "invalid_request_error")>
```

I have tried this in test mode, and it appears to work fine, but I need to try an actual payment which is why I've been using production mode - this is where the error is occurring. Hence the 'similar object exists in test mode' - I already have customers with the same address in test mode.

Then when I try to select a subscription:

```
<http_400 in doTryCatch(return(expr), name, parentenv, handler): Bad Request (HTTP 400).>
```

I also see the following 'Error in setup intent' message at the bottom of the screen whenever I try to select a subscription:

![image](https://user-images.githubusercontent.com/52550073/128083741-601dc99b-8527-4c8c-a3fd-deaf48b9acb5.png)

**Comment by merlinoa** [comment]
Thanks for the detail!  Yes currently you can only make a customer either in test mode or in production mode, not both.  I set it up this way because I have 2 separate databases (one for development and one for production) where I can separate out the users, but naturally you only have access production.  I'll update the package so that you can have a dev and production customer for each user.

I think the setup intent error is the same issue (i.e. we are sending the dev Stripe customer ID to your prod Stripe environment).  Thanks again for the bug report!

**Comment by nathhenry3** [comment]
That makes sense - tested with a new customer and it all appears to be working fine now. That was the last step for me - am currently building my app on Cloud Run and putting it into production in 2 hours.

Thank you so much!!

**Comment by merlinoa** [comment]
@nathhenry3 I just pushed the updates to the API and polishedpayments to distinguish between test and live Stripe customers.  Please install the lastest dev version of polishedpayments.

Unfortunately I am not sure which of your existing customers are live/test.  I set all the existing customers in the database to test customers, which will cause issues for any of your existing live Stripe customers.  If you can give me the emails of any your live Stripe customers I can manually update in the database.  You can email me the email addresses at andy.merlinoa@tychobra.com
