### ISSUE TITLE
remove_query_string not available

### ISSUE THREAD

**Issue by dcaud** [Tychobra/polishedpayments#3]
I'm trying to run the example, but get the following error:

> library(polishedpayments)
Error: package or namespace load failed for ‘polishedpayments’:
 object ‘remove_query_string’ is not exported by 'namespace:polished'

**Comment by merlinoa** [comment]
I think you just need the dev version of polished.  You can install with:

```
remotes::install_github("tychobra/polished")
```

Make sure to restart your R session after installing.

**Comment by dcaud** [comment]
That line produced:

Error in value[[3L]](cond) :
  Package ‘polished’ version 0.2.0 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘polished’ is imported by
‘polishedpayments’ so cannot be unloaded

**Comment by dcaud** [comment]
That worked!
