### ISSUE TITLE
Error in config::get() : 

### ISSUE THREAD

**Issue by dcaud** [Tychobra/polishedpayments#4]
I'm trying to run the example, and I get:

```
> runApp()
Error in config::get() : 
  Config file config.yml not found in current working directory or parent directories
```
I'm unsure whether I need to register with Stripe to use the example (or what the process is to create/get the config file).

I just cloned the example to my drive and opened the server file from within the relevant folder, so the working dir is 

~"polishedpayments-master/inst/examples/polished_payments_min" 

There is clearly not a config file in that directory, as the error message says.

**Comment by phoward38** [comment]
Hi @dcaud,

Yes, as described in the [README](https://github.com/Tychobra/polishedpayments/blob/master/README.md), you'll need to create a Stripe account & the corresponding `Product` & `Price(s)`, then provide the correct information to the `polished_payments_config` function. Keep in mind, you can provide this information directly to the argument without using a config file, but it's recommended over hardcoding sensitive information in your application.

I would start by looking at the `polished` example apps [source code](https://github.com/Tychobra/polished_example_apps) to see how we use `.yml` files as config files.

**Comment by dcaud** [comment]
Got it. I was kind of expecting the example to be self-contained, but now I
understand.  Thanks!
