### ISSUE TITLE
Dependency on polished 

### ISSUE THREAD

**Issue by johnbde** [Tychobra/polishedpayments#6]
Thanks for a great package. Just wondering if it can work without polished package as I have my own R module and function for login authentication?

**Comment by phoward38** [comment]
Thanks @johnbde, glad to hear you've enjoyed the package. The package is dependent upon `polished` since the user payment/subscription information is integrated with the existing user information in `polished`. I'm closing this issue, but feel free to reopen if you have any other questions.
