### ISSUE TITLE
One Time Purchase

### ISSUE THREAD

**Issue by johnbde** [Tychobra/polishedpayments#7]
Thank you for this great package. Does it not work with one time purchase?

**Comment by merlinoa** [comment]
Hi @johnbde 

No this package does not currently work with one time purchases.  However I am planning on getting back to development of this package in the next few weeks, and one time purchases will be one of the first features that I plan to implement.  I'll keep this issue open until it is done.

**Comment by bnovotny** [comment]
Is this feature still in development? Very interested in using it. Thanks!

**Comment by merlinoa** [comment]
We now have a shiny module to make one time payments.  Here is an examples of it in action:

server side of module: https://github.com/Tychobra/polishedpayments/blob/9a975fc7f5e89c3e437d2b4290c18f207b49524d/inst/examples/polished_payments_min/server.R#L35

ui side of module: https://github.com/Tychobra/polishedpayments/blob/9a975fc7f5e89c3e437d2b4290c18f207b49524d/inst/examples/polished_payments_min/ui.R#L62

Please install the latest version of polished and polishedpayments from GitHub to try it out.

**Comment by bnovotny** [comment]
Great! The module seems to be working for taking payments once a user is signed in. However, I’m wondering if it can be used to gate access to an app, the same as a subscription price ID in polished_payments_config(). It would be great to have the option for a customer to choose between a subscription or a one-time payment for access to the app. Thanks again for the great package!
